### ISSUE TITLE
Alpha channel issue

### ISSUE THREAD

**Issue by Wylwi** [LuisAlfredo92/Super-QOI-converter#1]
I tried encoding a PNG image to QOI using the converter : 
![PNG Image](https://user-images.githubusercontent.com/40737205/201488856-3597f0f3-1078-438d-8543-1fda8203544b.png)
The result is correct but not the channels number.
![image](https://user-images.githubusercontent.com/40737205/201488887-7d803c74-f33e-4fde-88e1-50fb9d12c11a.png)
It converted it to an image with alpha while there was initially no alpha channel

**Comment by LuisAlfredo92** [comment]
Thanks for the feedback

I'll check the number of channels of each image when reading it and the new image will have the same channels

**Comment by LuisAlfredo92** [comment]
It was easier than I thought

It should be fixed now, thanks for using the program 

Please ignore the commits messages, I wrote it but when I pushed it, it sounded a little rude although I was talking to me so I tried to amend it and it didn't work as I expected xD
